packages:
  - crates/tauri-plugin-hc
  - apps/holochain-runtime-example
  - '!**/android/**'
  - '!**/apple/**'
  - '!**/dist-js/**'
  - '!**/permissions/**'
allowBuilds:
  bufferutil: true
  es5-ext: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@holochain/client@0.21.0'
