packages:
  - crates/tauri-plugin-holochain
  - apps/holochain-runtime-example
  - '!**/android/**'
  - '!**/apple/**'
  - '!**/dist-js/**'
  - '!**/permissions/**'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@holochain/client@0.21.0'
