name: Build

on:
  pull_request:
    branches:
      - main
      - main-*

jobs:
  build-desktop:
    name: Build example (desktop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Build holochain-runtime-example
        run: |
          nix develop --no-update-lock-file --command bash -c "npm ci && npm run build:example && cargo build -p holochain-runtime-example"

  build-android:
    name: Build example (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: false
          swap-storage: false

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Build debug APK
        run: |
          nix develop --no-update-lock-file --command bash -c "npm ci && npm run build:example-android -- --debug --target x86_64 --apk"
